### ISSUE TITLE
Latest release: Error: Reference to undeclared input variable

### ISSUE THREAD

**Issue by nullreference8** [oracle-quickstart/oke-kubeflow#1]
`Error: Reference to undeclared input variable

  on modules/oke/data.tf line 7, in locals:

   7:   flex_shape = var.is_flex_shape ? [{ memory_in_gbs = var.node_pool_node_shape_config_memory_in_gbs, ocpus = var.node_pool_node_shape_config_ocpus }] : []

An input variable with the name "is_flex_shape" has not been declared. This

variable can be declared with a variable "is_flex_shape" {} block. `

When deploying the latest release zip file to the console, receiving the above error related to input variables.

**Comment by smithzc** [comment]
Fixed with commit f45b0a7
